### ISSUE TITLE
How to update svelte to last version

### ISSUE THREAD

**Issue by mahadoang** [meteor-svelte/meteor-svelte#19]
I love this package. this is easy to integrate with meteor.
But svelte update new version and How to update svelte to last version on my project

Thank you.

**Comment by klaussner** [comment]
Thanks, @mahadoang. :blush: Unfortunately, you can't update Svelte independently from `svelte:compiler` because versions of npm dependencies are fixed when the package is published on Atmosphere. That's a limitation of Meteor that will be removed in a future version (according to the "Compiling compiler plugins after installation" section of the [Meteor 1.8 release blog post](https://blog.meteor.com/meteor-1-8-erases-the-debts-of-1-7-77af4c931fe3)).

I've just published a new version of the package (2.15.0_1) with the latest version of Svelte, so it's up-to-date for now. :slightly_smiling_face:
