### ISSUE TITLE
svelte:compiler fails to compile svelte exports from js files

### ISSUE THREAD

**Issue by HorizonShadow** [meteor-svelte/meteor-svelte#27]
```
  import { Router, Link, Route } from "svelte-routing";
```

This fails when importing App.svelte on the server. 

```
C:\users\josh\documents\dev\aa2gd-meteor\node_modules\svelte-routing\src\Router.svelte:1
(function (exports, require, module, __filename, __dirname) { <script>
```

svelte-routing's index.js looks like this

```
export { default as Router } from "./Router.svelte";
export { default as Route } from "./Route.svelte";
export { default as Link } from "./Link.svelte";
export { navigate } from "./history.js";
export { link, links } from "./actions.js";
```

Importing directly works.

```
import Router from 'svelte-routing/src/Router';
```

I assume it's trying to import as a JS file rather than a svelte file.

**Comment by klaussner** [comment]
That's because the author of `svelte-routing` [doesn't compile the library before publishing it to npm](https://github.com/EmilTholin/svelte-routing/issues/52#issuecomment-505441024), which means that you have to tell Meteor to compile it at build time by creating a symbolic link to `svelte-routing` in your app directory:

```sh
cd <Meteor project>
ln -s node_modules/svelte-routing
```

Note: In the next Meteor version (1.8.2), [you will be able to (re)compile modules without this symlink workaround](https://github.com/meteor/meteor/pull/10603).
