### ISSUE TITLE
Babel transforms not applying to .svelte files

### ISSUE THREAD

**Issue by CaptainN** [meteor-svelte/meteor-svelte#31]
I've mostly ported [`svelte-loadable`](https://github.com/CaptainN/npdev-svelte-loadable) over to work with Meteor Svelte. The last piece of the puzzle is a ported babel plugin base on the one in [npdev:react-loadable](https://github.com/CaptainN/npdev-react-loadable/tree/master/babel), which makes configuration less verbose. That babel plugin though doesn't run on code specified in .svelte files. I would guess that means that other user configured babel plugins won't run either.

**Comment by klaussner** [comment]
I think that's because `Babel.compile` is called ([here](https://github.com/meteor-svelte/meteor-svelte/blob/2ec799a71ee0727a9ff7a2546d4dbd4862f66188/SvelteCompiler.js#L178)) with the default options provided by Meteor, which don't include Babel configuation from `.babelrc` or `package.json`. I will take a closer look next weekend.

**Comment by klaussner** [comment]
I changed how the Svelte output is compiled with Babel in https://github.com/meteor-svelte/meteor-svelte/pull/30/commits/984bd408af1bec23d0f5f284af757a011dbf7e7a (part of #30). Babel plugins from `.babelrc` should work in `svelte:compiler@4.0.0-beta.0`.

**Comment by CaptainN** [comment]
This appears to be working! Thanks!
